config_factory: [start, datasets/alphabattle_small/alphabattle_small, methods/tabsyn/base]

# setting up the optimal autoencoder
model:
  autoencoder:
    params:
      d_token: 64
      num_layers: 8
      n_head: 4
      factor: 10
    checkpoint: /home/transaction-generation/log/generation/
  
  latent_encoder:
    params:
      base_factor: 512 # unetXL

data_conf:
  train_resamples: 10
  val_ratio: 0.12
  train_transforms:
    '1':
      TimeToDiff:
        disable: true
  val_transforms:
    '1':
      TimeToDiff:
        disable: true

evaluator:
  devices: ["cuda:0", "cuda:0", "cuda:0"]
  metrics:
    - OTD
    - OTD: {f1_average: micro}
    - OTD: {focus_on: [amnt]}
    - OTD: {focus_on: [hours_since_first_tx]}
    - OTD: {focus_on: [mcc_category]}
    - OTD: {focus_on: [mcc_category], f1_average: micro}
    - OTD: {max_shift: 0, focus_on: [amnt]}
    - OTD: {max_shift: 0, focus_on: [hours_since_first_tx]}
    - OTD: {max_shift: 0, focus_on: [mcc_category]}
    - OTD: {max_shift: 0, focus_on: [mcc_category], f1_average: micro}
    - Cardinality
    - OTD: {global_denom: False}
    - OTD: {focus_on: [amnt], global_denom: False}
    - OTD: {focus_on: [hours_since_first_tx], global_denom: False}
    - Detection:
        report_std: True
        condition_len: ${data_conf.generation_len}
