config_factory: [start, datasets/alphabattle_small/alphabattle_small, methods/tabsyn/base, metrics/with_detection/alphabattle_small]

# setting up the optimal autoencoder
model:
  autoencoder:
    params:
      d_token: 64
      num_layers: 8
      n_head: 4
      factor: 10
    checkpoint: /home/transaction-generation/log/generation/
  
  latent_encoder:
    params:
      base_factor: 512 # unetXL

data_conf:
  train_resamples: 10
  val_ratio: 0.12
