log_dir: log/generation/age_11

data_conf:
  num_names:
  index_name: client_id
  time_name: trans_date
  focus_on:
    - small_group

  train_transforms:
    "log_tfs":
      Logarithm:
        names: []

  val_transforms:
    "log_tfs":
      Logarithm:
        names: []
