trainer:
  total_iters: 1_000_000
  total_epochs: null
  ckpt_track_metric: 'loss'
  iters_per_epoch: null
  patience: 10
  profiling: false
  verbose: True
  ckpt_resume: null

evaluator:
  metrics:
    - OTD
    - OTD: {f1_average: micro}
    - OTD: {focus_on: [amount_rur]}
    - OTD: {focus_on: [trans_date]}
    - OTD: {focus_on: [small_group]}
    - OTD: {focus_on: [small_group], f1_average: micro}
    - OTD: {max_shift: 0, focus_on: [amount_rur]}
    - OTD: {max_shift: 0, focus_on: [trans_date]}
    - OTD: {max_shift: 0, focus_on: [small_group]}
    - OTD: {max_shift: 0, focus_on: [small_group], f1_average: micro}
    - Cardinality
data_conf:
  dataset_name: age
  cat_cardinalities:
    - ["age", 5]
    - ["small_group", 203]
  num_names:
    - amount_rur
  index_name: client_id
  time_name: trans_date
  focus_on:
  target_token: "small_group"

  test_path: 'data/age/preprocessed/test'
  train_path: 'data/age/preprocessed/train'
  val_ratio: 0.15
  num_workers: 4
  train_resamples: 1
  batch_size: 512

  min_history_len: &min_history_len 32
  generation_len: &generation_len 32
  max_seq_len: &max_seq_len 1024

  padding_value: 0

  train_random_end: none
  val_random_end: time
  
  train_transforms:
    "rescale":
      RescaleTime:
        loc: 0
        scale: 730
        disable: True
    "time_diff":
      TimeToDiff:
        disable: false
    "log_time":
      "LogTime":
        disable: false
        clamp: 5
    "log_tfs":
      Logarithm:
        names: ["amount_rur"]
    "local_shuffle":
      LocalShuffle:
        max_shift: 0
    "3":
      CutTargetSequence:
        target_len: 0

  val_transforms:
    "rescale": ${data_conf.train_transforms.rescale}
    "time_diff": ${data_conf.train_transforms.time_diff}
    "log_time": ${data_conf.train_transforms.log_time}
    "log_tfs": ${data_conf.train_transforms.log_tfs}
    "3":
      CutTargetSequence:
        target_len: *generation_len
