trainer:
  total_iters: 1_000_000
  total_epochs: null
  ckpt_track_metric: 'Reconstruction overall'
  iters_per_epoch: null
  patience: 10
  profiling: false
  verbose: True
  ckpt_resume: null

log_dir: log/generation/age

# DATA
data_conf:
  cat_cardinalities:
    small_group: 203
  num_names:
  index_name: client_id
  time_name: trans_date
  focus_on:
    - small_group
  test_path: 'data/age/preprocessed/test'
  train_path: 'data/age/preprocessed/train'
  val_ratio: 0.15
  num_workers: 2
  train_resamples: 1
  batch_size: 128

  min_history_len: 32
  generation_len: &generation_len 32
  max_seq_len: 1024
  padding_value: 0

  train_random_end: none
  val_random_end: time
  
  train_transforms:
    "0":
      RescaleTime:
        loc: 0
        scale: 730
    "1":
      TimeToDiff:
        disable: false
    # "2":
    #   Logarithm:
    #     names: ["amount_rur"]
    # "shuffle":
    #   ShuffleBatch:
    #     untouched_slice: [None, None]

  val_transforms:
    "0":
      RescaleTime:
        loc: 0
        scale: 730
    "1":
      TimeToDiff:
        disable: false
    # "2":
    #   Logarithm:
    #     names: ["amount_rur"]
    # shuffle:
    #   ShuffleBatch:
    #     untouched_slice: [None, None]
    "2":
      CutTargetSequence:
        target_len: *generation_len
