log_dir: log/generation/mbd_11

data_conf:
  num_names:
  index_name: client_id
  time_name: days_since_first_tx
  focus_on:
    - event_type

  train_transforms:
    "log_tfs":
      Logarithm:
        names: []

  val_transforms:
    "log_tfs":
      Logarithm:
        names: []
