trainer:
  total_iters: 1_000_000
  total_epochs: null
  ckpt_track_metric: 'Reconstruction overall'
  iters_per_epoch: null
  patience: 10
  profiling: false
  verbose: True
  ckpt_resume: null

log_dir: log/generation/mbd

# DATA
data_conf:
  cat_cardinalities:
    src_type32: 88
    src_type11: 47
    event_subtype: 60
    dst_type11: 58
    event_type: 55
    currency: 13
    dst_type12: 253
    src_type22: 84
    src_type12: 188
    # src_type31: 1455
    # src_type21: 8000
  num_names:
    - amount
  index_name: client_id
  time_name: days_since_first_tx
  focus_on:

  test_path: 'data/mbd-50k/test'
  train_path: 'data/mbd-50k/train'
  val_ratio: 0.15
  num_workers: 2
  train_resamples: 1
  batch_size: 128

  min_history_len: 32
  generation_len: &generation_len 32
  max_seq_len: 1045
  padding_value: 0

  train_random_end: none
  val_random_end: time
  
  train_transforms:
    "0":
      RescaleTime:
        loc: 0.0
        scale: 365.0
    "1":
      TimeToDiff:
        disable: false
    "2":
      Logarithm:
        names: ["amount"]
    "3":
      CutTargetSequence:
        target_len: 0
    # "shuffle":
    #   ShuffleBatch:
    #     untouched_slice: [None, None]

  val_transforms:
    "0":
      RescaleTime:
        loc: 0.0
        scale: 365.0
    "1":
      TimeToDiff:
        disable: False
    "2":
      Logarithm:
        names: ["amount"]
    # shuffle:
    #   ShuffleBatch:
    #     untouched_slice: [None, None]
    "3":
      CutTargetSequence:
        target_len: *generation_len
