trainer:
  verbose: True

evaluator:
  devices:
  - cuda:1
  - cuda:2
  metrics:
  - Reconstruction
  - Levenshtein:
      target_key: event_type
  - F1Metric:
      target_key: event_type
      average: macro
  - F1Metric:
      target_key: event_type
      average: micro

  - CardinalityCoverage:
      target_key: event_type
      overall: False
  - CardinalityCoverage:
      target_key: event_type
      overall: True
  - NoveltyScore:
      target_key: event_type
      overall: False
  - NoveltyScore:
      target_key: event_type
      overall: True

  - Density:
      log_cols: ["amount"]
      with_timediff: True
      save_details: True
      verbose: True

  - Detection:
      dataset_config: detection/mbd
      method_config: gru
      condition_len: 32
      verbose: True

runner:
  name: GenerationEvaluator
  run_type: simple
  seed_keys:
  - common_seed
  params:
    n_runs: 1
    n_workers: 1
  device_list: null
