config_factory: [start, metrics/default, datasets/alphabattle_small/alphabattle_small, methods/gpt, 1to1]

optimizer:
  params:
    weight_decay: 8.222922690479135e-15
    lr: 0.00010917178681145987
model:
  latent_encoder:
    params:
      n_layer: 8
      n_head: 4
      n_embd: 400
      dropout: 0.16711961169726586
      bias: false
  autoencoder:
    params:
      num_norm: false
      cat_emb_dim: 8
      num_emb_dim: 5
data_conf:
  train_transforms:
    '1':
      TimeToDiff:
        disable: true
