config_factory:
  - datasets/mbd/mbd
  - methods/gru
  - datasets/mbd/metrics/default

# Runner params:
log_dir: log/generation
device: "cuda:1"

runner:
  name: GenerationTrainer
  run_type: simple
  seed_keys:
    - "common_seed"
  params:
    n_runs: 1
    n_workers: 1
  device_list:

logging:
  file_lvl: "info"
  cons_lvl: "info"