config_factory:
  - datasets/age/age
  - methods/mode
  - datasets/age/metrics/default

model:
  name:
  encoder:

# Runner params:
log_dir: log/generation
device: "cuda:1"
common_seed: 0

runner:
  name: GenerationEvaluator
  run_type: simple
  seed_keys:
    - "common_seed"
  params:
    n_runs: 1
    n_workers: 1
  device_list:

logging:
  file_lvl: "info"
  cons_lvl: "info"