config_factory:
  - datasets/zvuk/zvuk
  - methods/gru
  - datasets/zvuk/metrics/default
  - datasets/zvuk/cat_features_full

model:
  name:
  encoder:

data_conf.generation_len: 16

# Runner params:
log_dir: log/generation
device: "cuda:1"
common_seed: 0

runner:
  name: GenerationTrainer
  run_type: simple
  seed_keys:
    - "common_seed"
  params:
    n_runs: 1
    n_workers: 1
  device_list:

logging:
  file_lvl: "info"
  cons_lvl: "info"
