data_conf:
  batch_size: 128
  cat_cardinalities:
    currency: 2
    dst_type11: 55
    dst_type12: 253
    event_subtype: 60
    event_type: 54
    src_type11: 45
    src_type12: 184
    src_type22: 84
    src_type32: 87
  generation_len: 16
  index_name: client_id
  max_seq_len: 1045
  min_history_len: 16
  num_names:
  - amount
  num_workers: 0
  padding_value: 0.0
  test_path: data/mbd-50k/test
  time_name: days_since_first_tx
  train_path: data/mbd-50k/train
  train_random_end: none
  train_resamples: 1
  train_transforms:
  - RescaleTime:
      loc: 0.0
      scale: 365.0
  - TimeToFeatures:
      process_type: diff
  val_random_end: none
  val_ratio: 0
  val_transforms:
  - RescaleTime:
      loc: 0.0
      scale: 365.0
  - TimeToFeatures:
      process_type: diff
  - CutTargetSequence:
      target_len: 32
device: cuda:0
log_dir: log/generation
optimizer:
  name: Adam
  params:
    lr: 0.0003
    weight_decay: 0.0001
run_name: debug
scheduler:
  name: StepLR
  params:
    step_size: 30
trainer:
  ckpt_replace: true
  ckpt_resume: null
  ckpt_track_metric: epoch
  iters_per_epoch: 10000
  patience: -1
  profiling: false
  total_epochs: null
  total_iters: 100000
