evaluator:
  devices: ["cuda:1", "cuda:2"]
  metrics:
    - KLDiv
    - JSDiv
    - Levenshtein:
        target_key: category_id
    - MatchedReconstruction:
        max_shift: 0
    - MatchedReconstruction:
        max_shift: 32
    - Cardinality:
        target_key: category_id
    - F1Metric:
        target_key: category_id
        average: macro
    - F1Metric:
        target_key: category_id
        average: micro
    - Precision:
        target_key: category_id
        average: macro
    - Precision:
        target_key: category_id
        average: micro
    - Recall:
        target_key: category_id
        average: macro
    - Recall:
        target_key: category_id
        average: micro
    # - BatchCutMetric
    # - Density:
    #     log_cols: []
    #     with_timediff: True
    #     save_details: True
    #     verbose: False