trainer:
  total_iters: 1_000_000
  total_epochs: null
  ckpt_track_metric: "loss"
  iters_per_epoch: null
  patience: 10
  profiling: false
  verbose: True
  ckpt_resume: null

log_dir: log/generation/megamarket

# DATA
data_conf:
  cat_cardinalities:
    - ["category_id", 9844]
    - ["event", 5]
    # - ["item_id", 1447254]
  num_names:
    - price
  index_name: user_id
  time_name: hours_since_first_tx
  focus_on: 
  target_token: "category_id"

  test_path: 'data/megamarket-100k/test'
  train_path: 'data/megamarket-100k/train'
  val_ratio: 0.15
  num_workers: 4
  train_resamples: 1
  batch_size: 128

  min_history_len: &min_history_len 32
  generation_len: &generation_len 32
  max_seq_len: &max_seq_len 512
  padding_value: 0

  train_random_end: none
  val_random_end: time
  # loader_transforms:
  #   "0":
  #     ExcludeCategories:
  #       feature_name: "category_id"
  #       path: 'data/megamarket-100k/lfc.npy'
  #       gen_len: *generation_len
  #       min_hist_len: *min_history_len

  train_transforms:
    "0":
      RescaleTime:
        loc: 0.0
        scale: 60.0
    "1":
      TimeToDiff:
        disable: false
    "ngrams":
      NGramTransform:
        model_path: 'data/megamarket-100k/ngrams-mapper-32.pt'
        feature_name: category_id
        feature_counts: 9844
        max_l: *max_seq_len
        disable: true
    "log_tfs":
      Logarithm:
        names: ["price"]
    "local_shuffle":
      LocalShuffle:
        max_shift: 0
    "3":
      CutTargetSequence:
        target_len: 0

  val_transforms:
    "0":
      RescaleTime:
        loc: 0.0
        scale: 60.0
    "1":
      TimeToDiff:
        disable: false
    "log_tfs":
      Logarithm:
        names: ["price"]
    # shuffle:
    #   ShuffleBatch:
    #     untouched_slice: [None, None]
    "2":
      CutTargetSequence:
        target_len: ${data_conf.generation_len}
    
    "ngrams":
      NGramTransform:
        model_path: 'data/megamarket-100k/ngrams-mapper-32.pt'
        feature_name: category_id
        feature_counts: 9844
        max_l: *max_seq_len
        disable: true