trainer:
  total_iters: 1_000_000
  total_epochs: null
  ckpt_track_metric: 'Reconstruction overall'
  iters_per_epoch: null
  patience: 10
  profiling: false
  verbose: True
  ckpt_resume: null

# DATA
data_conf:
  cat_cardinalities:
    category_id: 7500
  index_name: user_id
  time_name: days_since_first_tx
  focus_on: 
    - category_id

  test_path: 'data/megamarket-50k/test'
  train_path: 'data/megamarket-50k/train'
  val_ratio: 0.15
  num_workers: 0
  train_resamples: 1
  batch_size: 64

  min_history_len: &min_history_len 32
  generation_len: &generation_len 32
  max_seq_len: 1045
  padding_value: 0

  train_random_end: none
  val_random_end: time
  loader_transforms:

  train_transforms:
    "0":
      RescaleTime:
        loc: 0.0
        scale: 365.0
    "1":
      TimeToDiff:
        disable: false
    # "shuffle":
    #   ShuffleBatch:
    #     untouched_slice: [None, None]
  val_transforms:
    "0":
      RescaleTime:
        loc: 0.0
        scale: 365.0
    "1":
      TimeToDiff:
        disable: false
    # shuffle:
    #   ShuffleBatch:
    #     untouched_slice: [None, None]
    "2":
      CutTargetSequence:
        target_len: *generation_len