trainer:
  total_iters: 1_000_000
  total_epochs: null
  ckpt_track_metric: 'loss'
  iters_per_epoch: null
  patience: 10
  profiling: false
  verbose: True
  ckpt_resume: null


# DATA
data_conf:
  dataset_name: datafusion
  cat_cardinalities:
    - ["mcc_code", 313]
  num_names:
    - transaction_amt
  index_name: user_id
  time_name: days_since_zero
  focus_on:
  target_token: "mcc_code"

  test_path: 'data/datafusion2023/test'
  train_path: 'data/datafusion2023/train'
  val_ratio: 0.15
  num_workers: 4
  train_resamples: 1
  batch_size: 128

  min_history_len: &min_history_len 32
  generation_len: &generation_len 32
  max_seq_len:  &max_seq_len 1045
  padding_value: 0

  train_random_end: none
  val_random_end: time

  train_transforms:
    "0":
      RescaleTime:
        loc: 0.0
        scale: 365.0
    "1":
      TimeToDiff:
        disable: True
    "log_tfs":
      Logarithm:
        names: ["transaction_amt"]
    "local_shuffle":
      LocalShuffle:
        max_shift: 0
    "3":
      CutTargetSequence:
        target_len: 0

  val_transforms:
    "0": ${data_conf.train_transforms.0}
    "1": ${data_conf.train_transforms.1}
    "log_tfs": ${data_conf.train_transforms.log_tfs}
    "3":
      CutTargetSequence:
        target_len: *generation_len