config_factory: [start, datasets/age/age, methods/oneshot/gru, oneshot/matched, allto1, metrics/default]

optimizer:
  params:
    weight_decay: 1.1784179611536313e-13
    lr: 0.0006886038657879542
model:
  latent_encoder:
    params:
      hidden_size: 679
      num_layers: 2
      dropout: 0.05863029389206066
  pooler: last
  autoencoder:
    params:
      num_norm: true
      cat_emb_dim: 93
      num_emb_dim: 76
data_conf:
  train_transforms:
    '1':
      TimeToDiff:
        disable: false
