config_factory: [start, metrics/default, datasets/age/age, methods/oneshot/gru, methods/oneshot/target, allto1]

optimizer:
  params:
    weight_decay: 5.197155479086596e-09
    lr: 5.356840503291662e-05
model:
  latent_encoder:
    params:
      hidden_size: 219
      num_layers: 8
      dropout: 0.003871575252178555
  autoencoder:
    params:
      num_norm: false
      cat_emb_dim: 84
      num_emb_dim: 67
data_conf:
  train_transforms:
    '1':
      TimeToDiff:
        disable: true
