config_factory: [start, metrics/default, datasets/age/age, methods/vae]

optimizer:
  params:
    weight_decay: 4.064923524024686e-12
    lr: 0.0042136867096942785
model:
  autoencoder:
    params:
      d_token: 8
      num_layers: 10
      n_head: 4
      factor: 28
data_conf:
  train_transforms:
    '1':
      TimeToDiff:
        disable: true
schedulers:
  step:
    StepLR:
      step_size: 50
  beta:
    BetaScheduler:
      init_beta: 0.4589620775364838
      factor: 0.6
      patience: 3
