# Params taken from log/generation/age/optuna/vae/120
# 0.998108	Reconstruction

config_factory: [start, datasets/age/age, methods/vae]

optimizer:
  params:
    weight_decay: 2.403583199337511e-11
    lr: 0.0023416397104011563
model:
  autoencoder:
    params:
      d_token: 72
      num_layers: 7
      n_head: 1
      factor: 2
data_conf:
  train_transforms:
    '1':
      TimeToDiff:
        disable: true
schedulers:
  step:
    StepLR:
      step_size: 30
  beta:
    BetaScheduler:
      init_beta: 0.8736339827501433
      factor: 0.5
      patience: 3
