config_factory: [start, metrics/detection, datasets/age/age, methods/adiff4tpp/base]


data_conf:
  train_transforms:
    '1':
      TimeToDiff:
        disable: True
  val_transforms:
    '1':
      TimeToDiff:
        disable: True

optimizer:
  name: Adam
  params:
    lr: 1e-5
    weight_decay: 1.e-9

evaluator:
  devices: ["cuda:0", "cuda:0"] # adjust for your hardware, ALWAYS SET MORE THAN 1 DEVICE (possible repeated)