config_factory: [start, metrics/detection, datasets/alphabattle_small/alphabattle_small, methods/adiff4tpp/base]

model:
  autoencoder:
    params:
      d_token: 64
      num_layers: 8
      n_head: 4
      factor: 10
    checkpoint: /trinity/home/j.chen/2.SeqDiff/transaction-generation/diffgen_vaes/vae_alphabattle_small.ckpt

  latent_encoder:
    params:
      latent_size: 384 ## d_token * num_features in training
      hidden_size: 2304 ## must be the times of laten_size



data_conf:
  batch_size: 500
  train_resamples: 10
  val_ratio: 0.12
  train_transforms:
    '1':
      TimeToDiff:
        disable: true
  val_transforms:
    '1':
      TimeToDiff:
        disable: true

optimizer:
  name: Adam
  params:
    lr: 1e-5
    weight_decay: 1.e-9

evaluator:
  devices: ["cuda:0", "cuda:0"] # adjust for your hardware ALWAYS SET MORE THAN 1 DEVICE (possible repeated)  
