evaluator:
  devices: ["cuda:1", "cuda:2"]
  topk: 1
  temperature: 1.
  metrics:
    - OTD
    - Levenshtein
    - Cardinality
    - MultisetF1Metric:
        average: macro
    - MultisetF1Metric:
        average: micro
    - F1Score:
        average: macro
    - F1Score:
        average: micro

    # - Density:
    #     log_cols: ["amount_rur"]
    #     with_timediff: True
    #     save_details: True
    #     verbose: False