evaluator:
  devices: ["cuda:1", "cuda:2"]
  topk: 1
  temperature: 1.
  metrics:
    - OTD
    - OTD:
        f1_average: micro
    - Cardinality
    - F1Metric:
        average: macro
    - F1Metric:
        average: micro
    - Detection:
        condition_len: ${data_conf.generation_len}
        verbose: True
    # - Density:
    #     log_cols: ["amount_rur"]
    #     with_timediff: True
    #     save_details: True
    #     verbose: False