evaluator:
  devices: ["cuda:1", "cuda:2"]
  metrics:
    - MatchedReconstruction:
        max_shift: 0
    - MatchedReconstruction:
        max_shift: 32
    - Levenshtein:
        target_key: behavior_type
    - F1Metric:
        target_key: behavior_type
        average: macro
    - F1Metric:
        target_key: behavior_type
        average: micro
    - Precision:
        target_key: behavior_type
        average: macro
    - Precision:
        target_key: behavior_type
        average: micro
    - Recall:
        target_key: behavior_type
        average: macro
    - Recall:
        target_key: behavior_type
        average: micro
    # - Density:
    #     log_cols: []
    #     with_timediff: True
    #     save_details: True
    #     verbose: False

    # - Detection:
    #     dataset_config: detection/mbd
    #     method_config: transformer
    #     condition_len: 0
    #     verbose: True

    # - Detection:
    #     dataset_config: detection/mbd
    #     method_config: gru
    #     condition_len: *generation_len
    #     verbose: True