config_factory: [start, datasets/alphabattle_small/alphabattle_small, methods/gru, 1to1, metrics/default]

optimizer:
  params:
    weight_decay: 2.3941517728696164e-05
    lr: 0.0009789375864001468
model:
  latent_encoder:
    params:
      hidden_size: 190
      num_layers: 2
      dropout: 1.2735936349073125e-07
  autoencoder:
    params:
      num_norm: false
      cat_emb_dim: 125
      num_emb_dim: 9
data_conf:
  train_transforms:
    '1':
      TimeToDiff:
        disable: false
