evaluator:
  devices: ["cuda:0", "cuda:0", "cuda:0"]
  metrics:
    - OTD
    - OTD: {f1_average: micro}
    - OTD: {focus_on: [amnt]}
    - OTD: {focus_on: [hours_since_first_tx]}
    - OTD: {focus_on: [mcc_category]}
    - OTD: {focus_on: [mcc_category], f1_average: micro}
    - OTD: {max_shift: 0, focus_on: [amnt]}
    - OTD: {max_shift: 0, focus_on: [hours_since_first_tx]}
    - OTD: {max_shift: 0, focus_on: [mcc_category]}
    - OTD: {max_shift: 0, focus_on: [mcc_category], f1_average: micro}
    - Cardinality
    - Detection:
        report_std: True
        condition_len: ${data_conf.generation_len}
        verbose: False
    - OTD: {global_denom: False}
    - OTD: {focus_on: [amnt], global_denom: False}
    - OTD: {focus_on: [hours_since_first_tx], global_denom: False}