method_name: conditioned_gru
runner_name: SupervisedRunner

loss:
  name: CrossEntropy

trainer:
  ckpt_track_metric: ${main_metric}
  metrics_on_train: true
  patience: ${patience}
  total_iters: 100_000

model:
  preprocess:
    name: ConditionGRU
    params:
      # Preprocess
      cat_cardinalities: ${cc}
      num_features: ${nn}
      cat_emb_dim: 16
      num_emb_dim: 16
      time_process: cat
      num_norm: True
      # GRU
      hidden_size: 128
      condition_path: /path_to_parquet
      num_layers: 1
  aggregation:
    name: ValidHiddenMean
  head:
    name: nn.Linear
    params:
      in_features: output_dim_from_prev
      out_features: ${n_classes}

optimizer:
  name: Adam
  params:
    lr: 3.e-4
    weight_decay: 1.e-7
