evaluator:
  devices: ["cuda:1", "cuda:2"]
  metrics:
    - Reconstruction
    - Levenshtein:
        target_key: CRR
    - F1Metric:
        target_key: CRR
        average: macro
    - F1Metric:
        target_key: CRR
        average: micro

    - Density:
        log_cols: ["Glucose"]
        with_timediff: True
        save_details: True
        verbose: False

    # - Detection:
    #     dataset_config: detection/mbd
    #     method_config: transformer
    #     condition_len: 0
    #     verbose: True

    # - Detection:
    #     dataset_config: detection/mbd
    #     method_config: gru
    #     condition_len: *generation_len
    #     verbose: True