config_factory: [start, datasets/shakespeare/shakespeare, methods/gru, 1to1, metrics/default]

optimizer:
  params:
    weight_decay: 2.546850393603085e-15
    lr: 0.001248159387521488
model:
  latent_encoder:
    params:
      hidden_size: 358
      num_layers: 2
      dropout: 8.65425491298879e-06
  autoencoder:
    params:
      num_norm: true
      cat_emb_dim: 95
      num_emb_dim: 46
data_conf:
  train_transforms:
    '1':
      TimeToDiff:
        disable: true
