config_factory: [start, datasets/shakespeare/shakespeare, methods/oneshot/gru, methods/oneshot/dist, allto1, metrics/default]

optimizer:
  params:
    weight_decay: 2.9543847801018673e-11
    lr: 0.000557430310887595
model:
  latent_encoder:
    params:
      hidden_size: 13
      num_layers: 5
      dropout: 8.03285250104053e-08
  pooler: last
  autoencoder:
    params:
      num_norm: false
      cat_emb_dim: 109
      num_emb_dim: 36
data_conf:
  train_transforms:
    '1':
      TimeToDiff:
        disable: false
