trainer:
  total_iters: 1_000_000
  total_epochs: null
  ckpt_track_metric: 'Reconstruction overall'
  iters_per_epoch: null
  patience: 10
  profiling: false
  verbose: True
  ckpt_resume: null

log_dir: log/generation/taobao

# DATA
data_conf:
  cat_cardinalities:
    - ["item_category", 1904]
    - ["behavior_type", 5]
  num_names:
  index_name: user_id
  time_name: time_since_tuesday
  focus_on:

  test_path: 'data/taobao/preprocessed/test'
  train_path: 'data/taobao/preprocessed/train'
  val_ratio: 0.15
  num_workers: 4
  train_resamples: 1
  batch_size: 128

  min_history_len: &min_history_len 32
  generation_len: &generation_len 32
  max_seq_len:  &max_seq_len 512
  padding_value: 0

  train_random_end: none
  val_random_end: time
  loader_transforms:
  train_transforms:
    "0":
      RescaleTime:
        loc: 0.0
        scale: 14.0
    "1":
      TimeToDiff:
        disable: false
    "ngrams":
      NGramTransform:
        model_path: 'data/taobao/preprocessed/ngrams-mapper-9995.pt'
        feature_name: behavior_type
        feature_counts: 5
        max_l: *max_seq_len
        disable: true
    "3":
      CutTargetSequence:
        target_len: 0

  val_transforms:
    "0":
      RescaleTime:
        loc: 0.0
        scale: 14.0
    "1":
      TimeToDiff:
        disable: false
    "3":
      CutTargetSequence:
        target_len: *generation_len
    "ngrams":
      NGramTransform:
        model_path: 'data/taobao/preprocessed/ngrams-mapper-9995.pt'
        feature_name: behavior_type
        feature_counts: 5
        max_l: *max_seq_len
        disable: true