config_factory: [start, datasets/alphabattle_small/alphabattle_small, methods/tabsyn/base, metrics/with_detection/alphabattle_small]

model:
  autoencoder:
    params:
      d_token: 64
      num_layers: 8
      n_head: 4
      factor: 10
    checkpoint: /home/transaction-generation/log/generation/ready/alphabattle_small/old_vae.ckpt
  latent_encoder:
    params:
      base_factor: 512 # unetXL
  params:
    history_encoder:
      checkpoint: /home/transaction-generation/log/generation/ready/alphabattle_small/dist.ckpt
      name: OneShotDistributionGenerator
      latent_encoder:
        name: GRU
        params:
          hidden_size: 604
          num_layers: 1
          dropout: 1.785708094771683e-10
      autoencoder:
        name: BaselineAE
        params:
          cat_emb_dim: 88
          num_emb_dim: 63
          num_norm: true
          use_time: true
        pretrain: false
        frozen: True
        checkpoint: null
        batch_transforms:
          - TimeToDiff:
              disable: false
      pooler: last
      params: null

data_conf:
  train_resamples: 10
  val_ratio: 0.15
