config_factory: [start, datasets/alphabattle_small/alphabattle_small, methods/tabsyn/base, metrics/with_detection/alphabattle_small]

model:
  autoencoder:
    params:
      d_token: 64
      num_layers: 8
      n_head: 4
      factor: 10
    checkpoint: /home/transaction-generation/log/generation/ready/alphabattle_small/old_vae.ckpt
  latent_encoder:
    params:
      base_factor: 512 # unetXL
  params:
    history_encoder:
      checkpoint: /home/transaction-generation/log/generation/ready/alphabattle_small/gru.ckpt
      name: AutoregressiveGenerator
      latent_encoder:
        name: GRU
        params:
          hidden_size: 200
          num_layers: 1
          dropout: 0.00010532607225017183
      autoencoder:
        name: BaselineAE
        params:
          cat_emb_dim: 51
          num_emb_dim: 18
          num_norm: true
          use_time: true
        pretrain: false
        frozen: True
        checkpoint: null
        batch_transforms:
      pooler: last
      params: null

data_conf:
  train_resamples: 10
  val_ratio: 0.15



# sh transaction-generation/zhores/simple.sh age/xl_default_frozen_gru 6-00
# sh transaction-generation/zhores/simple.sh age/xl_vae2_abs 6-00

# sh transaction-generation/zhores/simple.sh alphabattle_small/xl_default_frozen_gru 6-00
# sh transaction-generation/zhores/simple.sh alphabattle_small/xl_vae2_abs 6-00

# sh transaction-generation/zhores/simple.sh alphabattle_small/xl_default 6-00

# sh transaction-generation/zhores/simple.sh age/xl_vae2_diff 6-00
# sh transaction-generation/zhores/simple.sh alphabattle_small/xl_vae2_diff 6-00