config_factory: [start, metrics/default, datasets/mbd/mbd, methods/gpt, 1to1]

optimizer:
  params:
    weight_decay: 1.2250876157044167e-05
    lr: 0.0007452382874663753
model:
  latent_encoder:
    params:
      n_layer: 4
      n_head: 2
      n_embd: 448
      dropout: 0.5315379021826547
      bias: true
  autoencoder:
    params:
      num_norm: false
      cat_emb_dim: 120
      num_emb_dim: 122
data_conf:
  train_transforms:
    '1':
      TimeToDiff:
        disable: false
