config_factory: [start, datasets/mbd/mbd, methods/oneshot/gru, oneshot/matched, allto1, metrics/default]

optimizer:
  params:
    weight_decay: 8.52375197693584e-07
    lr: 0.00029840462714661453
model:
  latent_encoder:
    params:
      hidden_size: 727
      num_layers: 4
      dropout: 2.188405391027893e-05
  pooler: last
  autoencoder:
    params:
      num_norm: true
      cat_emb_dim: 122
      num_emb_dim: 112
data_conf:
  train_transforms:
    '1':
      TimeToDiff:
        disable: false
