config_factory: [start, datasets/mbd/mbd, methods/oneshot/gru, oneshot/target, allto1, metrics/default]

optimizer:
  params:
    weight_decay: 4.033113062312427e-06
    lr: 0.001467031712410606
model:
  latent_encoder:
    params:
      hidden_size: 261
      num_layers: 3
      dropout: 2.4910995823585155e-10
  pooler: last
  autoencoder:
    params:
      num_norm: true
      cat_emb_dim: 101
      num_emb_dim: 67
data_conf:
  train_transforms:
    '1':
      TimeToDiff:
        disable: true
