config_factory: [start, datasets/age/age, methods/tabsyn/base]

# setting up the optimal autoencoder
model:
  latent_encoder:
    name: ConditionalBridgeEncoder
    params:
      generation_len: 32
      history_len: 32
      history_encoder_dim: 256
      base_factor: 512
      dim_t: 1024
      num_classes: 1
      noise_schedule: ve
      gen_sampler: dbim # dbim for training!
      sampling_nfe: 65 # 50 for training!
      eta: 1.0
  autoencoder:
    params:
      d_token: 8
      num_layers: 10
      n_head: 4
      factor: 28
    checkpoint: /home/transaction-generation/log/generation/ready/old_vae_age.ckpt
  params:
    repeat_matching: True
  
  latent_encoder:
    params:
      base_factor: 512 # unetXL
data_conf:
  batch_size: 512
  train_resamples: 25
  train_transforms:
    '1':
      TimeToDiff:
        disable: true
  val_transforms:
    '1':
      TimeToDiff:
        disable: true

evaluator:
  devices: ["cuda:0", "cuda:0", "cuda:0"] # adjust for your hardware, ALWAYS SET MORE THAN 1 DEVICE (possible repeated)
  metrics:
    - OTD
    - OTD: {f1_average: micro}
    - OTD: {focus_on: [amount_rur]}
    - OTD: {focus_on: [trans_date]}
    - OTD: {focus_on: [small_group]}
    - OTD: {focus_on: [small_group], f1_average: micro}
    - OTD: {max_shift: 0, focus_on: [amount_rur]}
    - OTD: {max_shift: 0, focus_on: [trans_date]}
    - OTD: {max_shift: 0, focus_on: [small_group]}
    - OTD: {max_shift: 0, focus_on: [small_group], f1_average: micro}
    - Cardinality
    - Detection:
        report_std: True
        condition_len: ${data_conf.generation_len}
        verbose: False
    - OTD: {global_denom: False}
    - OTD: {focus_on: [amount_rur], global_denom: False}
    - OTD: {focus_on: [trans_date], global_denom: False}
