config_factory: [start, metrics/detection, datasets/age/age, methods/tabsyn/base]

# setting up the optimal autoencoder
model:
  autoencoder:
    params:
      d_token: 8
      num_layers: 10
      n_head: 4
      factor: 28
    checkpoint: /workspace/transactionsv2/transaction-generation/log/generation/age/debug/-(27)/seed_0/ckpt/epoch__0351_-_loss__-0.002042.ckpt
  
  latent_encoder:
    params:
      base_factor: 512 # unetXL
data_conf:
  train_transforms:
    '1':
      TimeToDiff:
        disable: true
  val_transforms:
    '1':
      TimeToDiff:
        disable: true

evaluator:
  devices: ["cuda:0", "cuda:0"] # adjust for your hardware, ALWAYS SET MORE THAN 1 DEVICE (possible repeated)