config_factory: [start, datasets/age/age, methods/tabsyn/base, metrics/with_detection/age]

model:
  autoencoder:
    params:
      d_token: 8
      num_layers: 10
      n_head: 4
      factor: 28
    checkpoint: /home/transaction-generation/log/generation/ready/age/old_vae.ckpt
  
  latent_encoder:
    params:
      base_factor: 512 # unetXL
      matching: True
