config_factory: [start, datasets/age/age, methods/tabsyn/base, metrics/with_detection/age]

model:
  latent_encoder:
    name: ConditionalBridgeEncoder
    params:
      generation_len: 32
      history_len: 32
      history_encoder_dim: 256
      base_factor: 512
      dim_t: 1024
      num_classes: 1
      noise_schedule: ve
      gen_sampler: dbim # dbim for training!
      sampling_nfe: 65 # 50 for training!
      eta: 1.0
  autoencoder:
    params:
      d_token: 8
      num_layers: 10
      n_head: 4
      factor: 28
    checkpoint: /home/transaction-generation/log/generation/ready/age/old_vae.ckpt
  params:
    repeat_matching: True

data_conf:
  batch_size: 512
  train_resamples: 25
