config_factory: [start, datasets/age/age, methods/tabsyn/base]

# setting up the optimal autoencoder
model:
  autoencoder:
    params:
      d_token: 40
      num_layers: 4
      n_head: 1
      factor: 5
    checkpoint: /home/transaction-generation/log/generation/ready/age_diff_vae.ckpt
  
  latent_encoder:
    params:
      base_factor: 512 # unetXL

data_conf:
  train_resamples: 50
  batch_size: 1024
  train_transforms:
    '1':
      TimeToDiff:
        disable: false
  val_transforms:
    '1':
      TimeToDiff:
        disable: false

optimizer:
  name: AdamW
  params:
    lr: 5.e-4
    weight_decay: 1.e-9

schedulers:
  "step":
    StepLR:
      step_size: 10
      gamma: 0.2

evaluator:
  devices: ["cuda:0", "cuda:0", "cuda:0"] # adjust for your hardware, ALWAYS SET MORE THAN 1 DEVICE (possible repeated)
  metrics:
    - OTD
    - OTD: {f1_average: micro}
    - OTD: {focus_on: [amount_rur]}
    - OTD: {focus_on: [trans_date]}
    - OTD: {focus_on: [small_group]}
    - OTD: {focus_on: [small_group], f1_average: micro}
    - OTD: {max_shift: 0, focus_on: [amount_rur]}
    - OTD: {max_shift: 0, focus_on: [trans_date]}
    - OTD: {max_shift: 0, focus_on: [small_group]}
    - OTD: {max_shift: 0, focus_on: [small_group], f1_average: micro}
    - Cardinality
    - Detection:
        report_std: True
        condition_len: ${data_conf.generation_len}
        verbose: False
    - OTD: {global_denom: False}
    - OTD: {focus_on: [amount_rur], global_denom: False}
    - OTD: {focus_on: [trans_date], global_denom: False}