config_factory: [start, datasets/age/age, methods/tabsyn/base, metrics/with_detection/age]

model:
  autoencoder:
    params:
      d_token: 72
      num_layers: 7
      n_head: 1
      factor: 2
    checkpoint: /home/transaction-generation/log/generation/ready/age/kl_vae.ckpt
    pretrain: True
  
  latent_encoder:
    params:
      base_factor: 512 # unetXL

optimizer:
  name: AdamW
  params:
    lr: 5.e-4
    weight_decay: 1.e-9

schedulers:
  "step":
    StepLR:
      step_size: 10
      gamma: 0.2
