config_factory: [start, datasets/age/age, methods/tabsyn/base, metrics/with_detection/age]

model:
  autoencoder:
    params:
      d_token: 40
      num_layers: 4
      n_head: 1
      factor: 5
    checkpoint: /home/transaction-generation/log/generation/ready/age/diff_vae.ckpt
    pretrain: True
    batch_transforms:
      - TimeToDiff:
          disable: False

  latent_encoder:
    params:
      base_factor: 512 # unetXL
