config_factory: [start, datasets/age/age, methods/tabsyn/base, metrics/with_detection/age]

model:
  autoencoder:
    params:
      d_token: 8
      num_layers: 10
      n_head: 4
      factor: 28
    checkpoint: /home/transaction-generation/log/generation/ready/age/old_vae.ckpt
  latent_encoder:
    params:
      base_factor: 512 # unetXL
  params:
    reference_seq: "history_encoder" # "repeat"
    history_encoder:
      checkpoint: /home/transaction-generation/log/generation/ready/age/detpp.ckpt
      name: DeTPP
      latent_encoder:
        name: GRU
        params:
          hidden_size: 386
          num_layers: 1
      autoencoder:
        name: BaselineAE
        params:
          cat_emb_dim: 88
          num_emb_dim: 109
          num_norm: true
          use_time: true
        pretrain: false
        frozen: True
        checkpoint: null
        batch_transforms:
          - RescaleTime:
              loc: 0
              scale: 0.0013698630136986301
      pooler: last
      params:
        k_factor: 1.0037504654857723