config_factory: [start, datasets/age/age, methods/tabsyn/base, metrics/with_detection/age]

model:
  autoencoder:
    params:
      d_token: 8
      num_layers: 10
      n_head: 4
      factor: 28
    checkpoint: /home/transaction-generation/log/generation/ready/age/old_vae.ckpt
  
  latent_encoder:
    params:
      base_factor: 512 # unetXL
  params:
    history_encoder:
      checkpoint: /home/transaction-generation/log/generation/ready/age/gru.ckpt
      name: AutoregressiveGenerator
      latent_encoder:
        name: GRU
        params:
          hidden_size: 480
          num_layers: 1
          dropout: 9.594490213419128e-06
      autoencoder:
        name: BaselineAE
        params:
          cat_emb_dim: 51
          num_emb_dim: 18
          num_norm: true
          use_time: true
        pretrain: false
        frozen: True
        batch_transforms:
      pooler: last
      params: null
