evaluator:
  devices: ["cuda:1", "cuda:2"]
  metrics:
    - Reconstruction
    - Levenshtein:
        target_key: event_type
    # - Accuracy:
    #     target_key: event_type
    - F1Metric:
        target_key: event_type
        average: macro
    - F1Metric:
        target_key: event_type
        average: micro
    - Precision:
        target_key: event_type
        average: macro
    - Precision:
        target_key: event_type
        average: micro
    - Recall:
        target_key: event_type
        average: macro
    - Recall:
        target_key: event_type
        average: micro
    # - Gini:
    #     target_key: event_type
    # - ShannonEntropy:
    #     target_key: event_type

    # - CardinalityCoverage:
    #     target_key: event_type
    #     overall: False
    # - CardinalityCoverage:
    #     target_key: event_type
    #     overall: True
    # - NoveltyScore:
    #     target_key: event_type
    #     overall: False
    # - NoveltyScore:
    #     target_key: event_type
    #     overall: True

    # - Density:
    #     log_cols: ["amount"]
    #     with_timediff: True
    #     save_details: True
    #     verbose: False

    # - Detection:
    #     dataset_config: detection/mbd
    #     method_config: transformer
    #     condition_len: 0
    #     verbose: True

    # - Detection:
    #     dataset_config: detection/mbd
    #     method_config: gru
    #     condition_len: *generation_len
    #     verbose: True