evaluator:
  devices: ["cuda:1", "cuda:2"]
  metrics:
    - MatchedReconstruction:
        max_shift: 0
    - MatchedReconstruction:
        max_shift: 32
    # - PR:
    #     target_key: event_type
    - Cardinality:
        target_key: event_type
    - F1Metric:
        target_key: event_type
        average: macro
    - F1Metric:
        target_key: event_type
        average: micro

    # - Gini:
    #     target_key: event_type
    # - ShannonEntropy:
    #     target_key: event_type

    # - CardinalityCoverage:
    #     target_key: event_type
    #     overall: False
    # - CardinalityCoverage:
    #     target_key: event_type
    #     overall: True
    # - NoveltyScore:
    #     target_key: event_type
    #     overall: False
    # - NoveltyScore:
    #     target_key: event_type
    #     overall: True

    # - Density:
    #     log_cols: ["amount"]
    #     with_timediff: True
    #     save_details: True
    #     verbose: False

    # - Detection:
    #     dataset_config: detection/mbd
    #     method_config: transformer
    #     condition_len: 0
    #     verbose: True

    # - Detection:
    #     dataset_config: detection/mbd
    #     method_config: gru
    #     condition_len: *generation_len
    #     verbose: True