evaluator:
  devices: ["cuda:1", "cuda:2"]
  topk: 1
  temperature: 1.
  metrics:
    - OTD: {max_shift: 0, detailed: True}

trainer:
  metrics_on_train: True

data_conf:
  train_transforms:
    "0":
      RescaleTime:
        loc: 0.0
        scale: 1
    "1":
      TimeToDiff:
        disable: False

model:
  name: BaselineAE
  autoencoder:
    name: BaselineAE
    params:
      cat_emb_dim: 16
      num_emb_dim: 16
      num_norm: True
      use_time: True
    pretrain: True
    frozen: False
    checkpoint:
    batch_transforms:
  latent_encoder:

optimizer:
  name: Adam
  params:
    lr: 5e-2
    weight_decay: 1.e-6

schedulers:
  "plate":
    ReduceLROnPlateau:
      factor: 0.1
      patience: 3
      threshold: 0.01
  # "step":
  #   StepLR:
  #     step_size: 30


loss:
  name: AELoss
  params:
    l2_coef: 1e-4
    mse_weight: 0.5

