method_name: gru
runner_name: InsightsRunner

loss:
  name: CrossEntropy

trainer:
  ckpt_track_metric: ${main_metric}
  metrics_on_train: true
  patience: ${patience}
  total_iters: 100_000

model:
  preprocess:
    name: Batch2Seq
    params:
      cat_cardinalities: ${cc}
      num_features: ${nn}
      cat_emb_dim: 16
      num_emb_dim: 16
      time_process: "cat" # "diff" | "cat" | "none"
      num_norm: true
  encoder: 
    name: GRU
    params:
      input_size: output_dim_from_prev
      hidden_size: 128
      num_layers: 1
      dropout: 0.
      initial_hidden: static
  aggregation:
    name: ValidHiddenMean
  head:
    name: nn.Linear
    params:
      in_features: output_dim_from_prev
      out_features: ${n_classes}

optimizer:
  name: Adam
  params:
    lr: 3.e-4
    weight_decay: 1.e-7

