trainer:
  metrics_on_train: False
  total_iters: 10_000_000 # may be it is too much...

evaluator:
  devices: ["cuda:0", "cuda:1"]


data_conf:
  train_resamples: 50
  batch_size: 1024
  train_transforms:
    '1':
      TimeToDiff:
        disable: False 
    "3":
      CutTargetSequence:
        #target_len: ${data_conf.generation_len}
        target_len: 32
  val_transforms:
    '1':
      TimeToDiff:
        disable: False


# MODEL
model:
  name: ContinuousDiscreteDiffusionGenerator1
  params:
    history_len: 32
    generation_len:  ${data_conf.generation_len}
    scheduler: power_mean_per_column
    cat_scheduler: log_linear_per_column
    noise_dist: uniform_t
    edm_params:
      'precond': True
      'sigma_data': 1.0
      'net_conditioning': sigma
    noise_dist_params:
      'P_mean': 1.2
      'P_std': -1.2
    sampler_params:
      'stochastic_sampler': True 
      'second_order_correction': True 
    noise_schedule_params:
      'sigma_min': 0.002
      'sigma_max': 80
      'rho': 7
      'eps_max': 0.001
      'eps_min': 1e-05 
      'rho_init': 7.0 
      'rho_offset': 5.0 
      'k_init': -6.0
      'k_offset': 1.0
    unet_params:
      'd_token': 4
      'length':   ${data_conf.generation_len}
      'rawhist_length': 32
      'with_transformer': True
      'num_layers': 4
      'n_head': 2
      'factor': 32
    cond_col:


optimizer:
  name: Adam
  params:
    lr: 1.e-5 # Note: I didn't adjust hyperparams&schedulers
    weight_decay: 1.e-9

schedulers:
  "step":
    StepLR: # Note: I didn't adjust hyperparams&schedulers
      step_size: 30


loss:
  name: DummyLoss


optuna:
  params:
    n_trials: 100
    n_startup_trials: 10
    request_list: []
    target_metric: ${trainer.ckpt_track_metric}
  suggestions:


    - ["optimizer.params.weight_decay", ["suggest_float", {low: 1.e-15, high: 1.e-2, log: True}]]
    - ["optimizer.params.lr", ["suggest_float", {low: 1.e-5, high: 0.1, log: True}]]

    - ['model.params.sampler_params.stochastic_sampler',["suggest_categorical", {choices: [True, False]}]]
    - ['model.params.sampler_params.second_order_correction',["suggest_categorical", {choices: [True, False]}]]

    - ["model.params.unet_params.d_token", ["suggest_int", {low: 4, high: 20, log: False}]]
    - ["model.params.unet_params.num_layers", ["suggest_int", {low: 4, high: 24, log: False}]]
    - ["model.params.unet_params.factor", ["suggest_int", {low: 12, high: 32, log: False}]]

    - 
      - ["data_conf.train_transforms.1.TimeToDiff.disable", "data_conf.val_transforms.1.TimeToDiff.disable"]
      - ["suggest_categorical", {choices: [True, False]}]