config_factory: [start, datasets/taobao/taobao, methods/gpt, 1to1, metrics/default]

optimizer:
  params:
    weight_decay: 7.786918399449843e-10
    lr: 0.003494535896596293
model:
  latent_encoder:
    params:
      n_layer: 7
      n_head: 1
      n_embd: 208
      dropout: 0.3551286214308489
      bias: true
  autoencoder:
    params:
      num_norm: false
      cat_emb_dim: 116
      num_emb_dim: 61
data_conf:
  train_transforms:
    '1':
      TimeToDiff:
        disable: false
