config_factory: [start, datasets/taobao/taobao, methods/gru, 1to1, metrics/default]

optimizer:
  params:
    weight_decay: 2.6551840722067854e-05
    lr: 0.0028516257149803857
model:
  latent_encoder:
    params:
      hidden_size: 587
      num_layers: 2
      dropout: 9.793558359587279e-07
  autoencoder:
    params:
      num_norm: true
      cat_emb_dim: 97
      num_emb_dim: 8
data_conf:
  train_transforms:
    '1':
      TimeToDiff:
        disable: true
