config_factory: [start, datasets/retail/retail, methods/gpt, 1to1, metrics/default]

optimizer:
  params:
    weight_decay: 1.5429769361370426e-13
    lr: 0.00016912601015410544
model:
  latent_encoder:
    params:
      n_layer: 11
      n_head: 16
      n_embd: 176
      dropout: 0.1831228989111418
      bias: true
  autoencoder:
    params:
      num_norm: false
      cat_emb_dim: 41
      num_emb_dim: 60
data_conf:
  train_transforms:
    '1':
      TimeToDiff:
        disable: true
