config_factory: [start, datasets/retail/retail, methods/oneshot/gru, oneshot/dist, allto1, metrics/default]

optimizer:
  params:
    weight_decay: 1.8969655101517064e-06
    lr: 3.0853544101321125e-05
model:
  latent_encoder:
    params:
      hidden_size: 961
      num_layers: 3
      dropout: 0.0001597164244797367
  pooler: last
  autoencoder:
    params:
      num_norm: true
      cat_emb_dim: 86
      num_emb_dim: 14
data_conf:
  train_transforms:
    '1':
      TimeToDiff:
        disable: true
