log_dir: log/datafusion_detection
patience: 2
n_classes: 2
main_metric: MulticlassAUROC
main_loss: 
  name: nn.CrossEntropyLoss

cc: 
  mcc_code: 332
  currency_rk: 4
  customer_age: 4
nn:
  - transaction_amt

data:
  dataset:
    parquet_path: "data/datafusion/discrimination/data"
    random_split: true
    split_seed: 42

    split_sizes: 
      - 0.7   # train
      - 0.15  # train_val
      - 0.15  # test

  preprocessing:
    common_pipeline: &common_pipeline
      max_seq_len: 1000
      time_name: days_since_first_tx
      index_name: user_id
      target_name: generated
      cat_cardinalities: ${cc}
      num_names: ${nn}
      batch_transforms:
        - RescaleTime:
            loc: 0.0
            scale: 183
        - TimeToFeatures:
            process_type: ${model.preprocess.params.time_process}
        - FillNans:
            fill_value: 0.0
    contrastive_pipeline:
      <<: *common_pipeline
      batch_transforms:
        - RescaleTime:
            loc: 0.0
            scale: 1000.0
        - TimeToFeatures:
            process_type: ${model.preprocess.params.time_process}
        - ContrastiveTarget
        - RandomSlices:
            split_count: 5
            cnt_min: 25
            cnt_max: 200
            short_seq_crop_rate: 0.8
            seed: 0

  loaders:
    train:
      split_idx: 0
      preprocessing: common_pipeline
      batch_size: 128
      drop_incomplete: true
      shuffle: true
      loop: false
      num_workers: 4
      random_seed: 42
    full_train:
      split_idx: 0
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4
    train_val:
      split_idx: 1
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4
    hpo_val:
      split_idx: 2
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4

test_data:
  dataset:
    parquet_path: ${data.dataset.parquet_path}
    split_sizes: 
      - 0.0
  preprocessing:
    common_pipeline: *common_pipeline
  loaders:
    test:
      split_idx: 0
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4

metrics:
  - name: ${main_metric}
    params: 
      num_classes: ${n_classes}
