log_dir: log/mbd/embeddings
patience: 5

cc:
  event_type: 19
  src_type11: 11
  dst_type11: 13
  src_type32: 37 
nn:
  - amount

data:
  dataset:
    parquet_path: 
    random_split: true
    split_seed: 42

    split_sizes: 
      - 0.85   # train
      - 0.15  # train_val

  preprocessing:
    common_pipeline: &common_pipeline
      max_seq_len: 150
      time_name: event_time
      index_name: client_id
      target_name: 
      cat_cardinalities: ${cc}
      num_names: ${nn}
      batch_transforms:
        # - DatetimeToFloat:
        #     loc: "2022-01-01"
        #     scale: [365, "D"]
        - RescaleTime:
            loc: 18627.879954
            scale: 545.0522569444438
        - TimeToFeatures:
            process_type: ${model.preprocess.params.time_process}
        - MaskValid
        - Logarithm:
            names: ["amount"]
    contrastive_pipeline:
      <<: *common_pipeline
      batch_transforms:
        # - DatetimeToFloat:
        #     loc: "2022-01-01"
        #     scale: [365, "D"]
        - RescaleTime:
            loc: 18627.879954
            scale: 545.0522569444438
        - TimeToFeatures:
            process_type: ${model.preprocess.params.time_process}
        - MaskValid
        - Logarithm:
            names: ["amount"]
        - ContrastiveTarget
        - RandomSlices:
            split_count: 5
            cnt_min: 10
            cnt_max: 100
            short_seq_crop_rate: 0.8
            seed: 0

  loaders:
    full_train:
      split_idx: 0
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4
      labeled: False
    train_val:
      split_idx: 1
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4
      labeled: False
    # for training:
    unsupervised_train:
      split_idx: 0
      preprocessing: contrastive_pipeline
      batch_size: 128
      shuffle: true
      num_workers: 4
      labeled: False
    unsupervised_train_val:
      split_idx: 1
      preprocessing: contrastive_pipeline
      batch_size: 128
      num_workers: 4
      labeled: False

