log_dir: log/mbd_detection
patience: 2
n_classes: 2
main_metric: MulticlassAUROC
main_loss: 
  name: nn.CrossEntropyLoss

cc:
  event_type: 21
  event_subtype: 19
  currency: 2
  src_type11: 9
  src_type12: 16
  dst_type11: 12
  dst_type12: 16
  src_type21: 16
  src_type22: 51
  src_type31: 31
  src_type32: 37 
nn:
  - amount

data:
  dataset:
    parquet_path: "data/mbd/detection/data"
    random_split: true
    split_seed: 42

    split_sizes: 
      - 0.7   # train
      - 0.15  # train_val
      - 0.15  # test

  preprocessing:
    common_pipeline: &common_pipeline
      max_seq_len: 150
      time_name: days_since_first_tx
      index_name: client_id
      target_name: generated
      cat_cardinalities: ${cc}
      num_names: ${nn}
      batch_transforms:
        - DatetimeToFloat:
            loc: "2022-01-01"
            scale: [365, "D"]
        - TimeToFeatures:
            process_type: ${model.preprocess.params.time_process}
        - TargetToLong
        - MaskValid
        - Logarithm:
            names: ["amount"]

  loaders:
    train:
      split_idx: 0
      preprocessing: common_pipeline
      batch_size: 128
      drop_incomplete: true
      shuffle: true
      loop: false
      num_workers: 4
      random_seed: 42
    full_train:
      split_idx: 0
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4
    train_val:
      split_idx: 1
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4
    hpo_val:
      split_idx: 2
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4

test_data:
  dataset:
    parquet_path: ${data.dataset.parquet_path}
    split_sizes: 
      - 0.0
  preprocessing:
    common_pipeline: *common_pipeline
  loaders:
    test:
      split_idx: 0
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4

metrics:
  - name: ${main_metric}
    params: 
      num_classes: ${n_classes}
