evaluator:
  devices: ["cuda:1", "cuda:2"]
  metrics:
    - KLDiv
    - JSDiv
    - Levenshtein:
        target_key: level_2
    - MatchedReconstruction:
        max_shift: 0
    - MatchedReconstruction:
        max_shift: 32
    - Cardinality:
        target_key: level_2
    - Levenshtein:
        target_key: level_2
    - F1Metric:
        target_key: level_2
        average: macro
    - F1Metric:
        target_key: level_2
        average: micro
    - Precision:
        target_key: level_2
        average: macro
    - Precision:
        target_key: level_2
        average: micro
    - Recall:
        target_key: level_2
        average: macro
    - Recall:
        target_key: level_2
        average: micro
    - Density:
        log_cols: ["purchase_sum"]
        with_timediff: True
        save_details: True
        verbose: False

    # - Detection:
    #     dataset_config: detection/mbd
    #     method_config: transformer
    #     condition_len: 0
    #     verbose: True

    # - Detection:
    #     dataset_config: detection/mbd
    #     method_config: gru
    #     condition_len: *generation_len
    #     verbose: True