config_factory: [start, datasets/zvuk/zvuk, methods/gru, 1to1, metrics/default]

optimizer:
  params:
    weight_decay: 1.237983757427686e-10
    lr: 0.002651754827709598
model:
  latent_encoder:
    params:
      hidden_size: 262
      num_layers: 2
      dropout: 7.062123277383907e-09
  autoencoder:
    params:
      num_norm: false
      cat_emb_dim: 77
      num_emb_dim: 124
data_conf:
  train_transforms:
    '1':
      TimeToDiff:
        disable: true
