config_factory: [start, datasets/zvuk/zvuk, methods/oneshot/gru, oneshot/dist, allto1, metrics/default]

optimizer:
  params:
    weight_decay: 1.7136827739651052e-05
    lr: 0.0008206868630501359
model:
  latent_encoder:
    params:
      hidden_size: 242
      num_layers: 2
      dropout: 1.3679908089335904e-08
  pooler: last
  autoencoder:
    params:
      num_norm: false
      cat_emb_dim: 82
      num_emb_dim: 123
data_conf:
  train_transforms:
    '1':
      TimeToDiff:
        disable: true
