config_factory: [start, datasets/megamarket/megamarket, methods/gpt, 1to1, metrics/default]

optimizer:
  params:
    weight_decay: 5.35660215714882e-10
    lr: 0.0013007341377986284
model:
  latent_encoder:
    params:
      n_layer: 9
      n_head: 8
      n_embd: 272
      dropout: 0.44336899799547025
      bias: false
  autoencoder:
    params:
      num_norm: false
      cat_emb_dim: 106
      num_emb_dim: 101
data_conf:
  train_transforms:
    '1':
      TimeToDiff:
        disable: false
