config_factory: [start, datasets/megamarket/megamarket, methods/gru, 1to1, metrics/default]

optimizer:
  params:
    weight_decay: 6.664693493282924e-06
    lr: 0.0002875878861952289
model:
  latent_encoder:
    params:
      hidden_size: 400
      num_layers: 5
      dropout: 1.4997282360909037e-10
  autoencoder:
    params:
      num_norm: false
      cat_emb_dim: 127
      num_emb_dim: 58
data_conf:
  train_transforms:
    '1':
      TimeToDiff:
        disable: true
