config_factory: [start, datasets/megamarket/megamarket, methods/oneshot/gru, oneshot/target, allto1, metrics/default]

optimizer:
  params:
    weight_decay: 2.1989718856646913e-05
    lr: 0.0015187086530692659
model:
  latent_encoder:
    params:
      hidden_size: 95
      num_layers: 1
      dropout: 0.0006408735652885512
  pooler: last
  autoencoder:
    params:
      num_norm: false
      cat_emb_dim: 79
      num_emb_dim: 58
data_conf:
  train_transforms:
    '1':
      TimeToDiff:
        disable: false
